/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.81
 * Generated at: 2017-12-10 05:50:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_005fmain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	request.setCharacterEncoding("utf-8");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("        \r\n");
      out.write("    <title>SIGN-UP Eat It</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap -->\r\n");
      out.write("    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- font awesome -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/font-awesome.min.css\" media=\"screen\" title=\"no title\" charset=\"utf-8\">\r\n");
      out.write("    <!-- Custom style -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\" media=\"screen\" title=\"no title\" charset=\"utf-8\">\r\n");
      out.write("\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("\t<form name=\"join_form\" action=\"UserJoinAction\" method=\"post\">\r\n");
      out.write("      <article class=\"container\">\r\n");
      out.write("        <div class=\"page-header\">\r\n");
      out.write("          <h1>회원가입 <small>Sign up for 'EAT IT!'</small></h1>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-6 col-md-offset-3\">\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("              <label for=\"InputId\">아이디</label>\r\n");
      out.write("              <input type=\"text\" name=\"user_id\" class=\"form-control\" id=\"Id\" placeholder=\"아이디\">\r\n");
      out.write("            </div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("              <label for=\"InputPassword1\">비밀번호</label>\r\n");
      out.write("              <input type=\"password\" name=\"user_password\" class=\"form-control\" id=\"Password\" placeholder=\"비밀번호\">\r\n");
      out.write("            </div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("              <label for=\"InputPassword2\">비밀번호 확인</label>\r\n");
      out.write("              <input type=\"password\" name=\"user_password_check\" class=\"form-control\" id=\"Password2\" placeholder=\"비밀번호 확인\">\r\n");
      out.write("              <p class=\"help-block\">비밀번호 확인을 위해 다시 한번 입력 해 주세요</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("              <label for=\"username\">이름</label>\r\n");
      out.write("              <input type=\"text\" name=\"user_name\" class=\"form-control\" id=\"Name\" placeholder=\"이름을 입력해 주세요\">\r\n");
      out.write("            </div>\r\n");
      out.write("                     \r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("              <label for=\"InputEmail\">전화 번호</label>\r\n");
      out.write("              <input type=\"text\" name=\"user_phone\"class=\"form-control\" id=\"PhoneNum\" placeholder=\"전화 번호를 입력해 주세요\">\r\n");
      out.write("              \r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("              <label for=\"InputEmail\">이메일 주소</label>\r\n");
      out.write("              <input type=\"email\" name=\"user_email\" class=\"form-control\" id=\"Email\" placeholder=\"이메일 주소를 입력해 주세요\">\r\n");
      out.write("            </div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("            <div class=\"form-group text-center\">\r\n");
      out.write("              <button type=\"submit\" class=\"btn btn-info\" onclick=\"RegisterUser()\">회원가입<i class=\"fa fa-check spaceLeft\"></i></button>\r\n");
      out.write("              <button type=\"submit\" class=\"btn btn-warning\">가입취소<i class=\"fa fa-times spaceLeft\"></i></button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      </article>\r\n");
      out.write("\t</form>\r\n");
      out.write("    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js\"></script>\r\n");
      out.write("    <!-- Include all compiled plugins (below), or include individual files as needed -->\r\n");
      out.write("    <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("  </body>\r\n");
      out.write("  \r\n");
      out.write("<div class=\"footer\">\r\n");
      out.write("<br>\r\n");
      out.write("@Copyright Son, Oh, Lee \r\n");
      out.write("<br>\r\n");
      out.write("Advanced Web Programming Team7\r\n");
      out.write("</div>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
